FROM ubuntu
ENV PORT 8081
RUN apt-get update -y
RUN apt-get install -y python-pip python-dev build-essential
COPY ./requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip install -r requirements.txt
COPY ./app/app.py /app/app.py
ENTRYPOINT ["python3"]
CMD ["app.py"]
