version: '3.7'
services:
    flask:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/app
        environment:
            - REDIS_HOST=redis
environment:
    - MEMCACHED_PASSWORD=password123
        depends_on:
            - memcached
    memcached:
        image: bitnami/memcached
        ports:
            - "11211:11211"